name: Run tests on CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test-without-container:
    name: Test without container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fish
        run: |
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt update
          sudo apt install fish
      - name: Install Just command runner
        run: sudo snap install --edge --classic just
      - name: Print Fish version
        run: fish --version
      - name: Install Fisher && Fishtape && Project
        run: |
          curl -sL https://git.io/fisher | source
          fisher install \
            jorgebucaran/fisher \
            jorgebucaran/fishtape \
            ./
        shell: fish {0}
      - name: Install Saml2aws
        run: |
          CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
          mkdir -p ~/.local/bin
          wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz -O - | tar -xzv -C ~/.local/bin
          chmod u+x ~/.local/bin/saml2aws
      - name: Print saml2aws version
        run: saml2aws --version
      - name: Test project
        run: just test-without-container

  test-inside-container:
    name: Test on fish ${{ matrix.fish_version }} on Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fish_version:
          - '3.1.2'
    steps:
      - uses: actions/checkout@v2
      - name: Install Fish
        run: |
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt update
          sudo apt install fish
      - name: Install Just command runner
        run: sudo snap install --edge --classic just
      - name: Build image
        run: just FISH_VERSION=3.1.2 build-project-on
      - name: Print saml2aws version
        run: just FISH_VERSION=3.1.2 CMD="saml2aws --version" dev-project-on
      - name: Test project
        run: just FISH_VERSION=3.1.2 test-project-on
